---
- hosts: all
  roles:
    - common

- name: neutron code and config
  hosts: controller:db:compute:network
  vars_files:
    - roles/rabbitmq/defaults/main.yml
  roles:
    - neutron-common

- hosts: network:compute
  roles:
    - openvswitch

- name: start neutron-openvswitch-agent
  hosts: network:compute
  tasks:
    - service: name=neutron-openvswitch-agent state=started

- name: nova code and config
  hosts: controller:db:compute
  vars_files:
    - roles/rabbitmq/defaults/main.yml
  roles:
    - nova-common

- name: cinder code and config
  hosts: controller:db:compute
  vars_files:
    - roles/rabbitmq/defaults/main.yml
  roles:
    - cinder-common

- name: openstack client tools
  hosts: all
  roles:
    - client

- hosts: compute
  roles:
    - compute
    - cinder-volume

- name: Install monitoring
  include: playbooks/monitoring.yml
