---
- name: Check if neutron user exists
  action: shell getent passwd neutron
  register: neutron_user
  ignore_errors: True
  changed_when: False

- name: neutron user
  user: name=neutron shell=/bin/false createhome=no
  when: neutron_user.rc == 0

- name: neutron user
  user: name=neutron comment=neutron shell=/bin/false system=yes home=/nonexistent createhome=no
  when: neutron_user.rc != 0

- name: get neutron source repo
  git: |
    repo={{ openstack.git_mirror }}/neutron.git
    dest=/opt/stack/neutron
    version={{ neutron.rev }}
    update={{ openstack.git_update }}
  register: result
  until: result|success
  retries: 3
  delay: 60

- shell: patch -p0 -N --dry-run --silent < /opt/stack/neutron/fix-ovs-klm-version-detection.patch 2>/dev/null; echo $?
  register: neutron.ovs_patch

# Patch around neutron's Open vSwitch kernel module version detection
# Problem is now that Open vSwitch is merged into mainline kernel
# modinfo openvswitch no longer includes a version: field
- template: src=opt/stack/neutron/fix-ovs-klm-version-detection.patch dest=/opt/stack/neutron/fix-ovs-klm-version-detection.patch mode=0644
- shell: patch -p1 < fix-ovs-klm-version-detection.patch chdir=/opt/stack/neutron
  when: neutron.ovs_patch == 0 # 0 if patch needs to be applied, otherwise 1 if already applied.
  notify:
    - pip install neutron
    - neutron rootwrap
    - restart neutron services
- meta: flush_handlers

- file: dest=/etc/neutron state=directory
- file: dest=/etc/neutron/plugins/openvswitch state=directory
- file: dest=/etc/neutron/services/loadbalancer/haproxy state=directory
- file: dest=/var/lib/neutron state=directory owner=neutron
- file: dest=/var/cache/neutron state=directory mode=0700 owner=neutron group=neutron

- name: neutron config
  action: template src={{ item }} dest=/etc/neutron mode=0644
  with_fileglob: ../templates/etc/neutron/*
  notify:
     - restart neutron services

- name: neutron dnsmasq config
  action: template src=etc/dnsmasq.conf dest=/etc/dnsmasq.conf mode=0644
  notify:
     - restart neutron services

- template: |
    src=etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
    dest=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
    mode=0644
  notify:
    - restart neutron services

- template: |
    src=etc/neutron/services/loadbalancer/haproxy/lbaas_agent.ini
    dest=/etc/neutron/services/loadbalancer/haproxy/lbaas_agent.ini
    mode=0644
  notify:
    - restart neutron services

- name: neutron sudoer
  template: src=etc/sudoers.d/neutron dest=/etc/sudoers.d/neutron owner=root group=root mode=0440

